### ISSUE TITLE
PolySharp won't work on ASP.NET MVC Projects

### ISSUE THREAD

**Issue by ssg** [Sergio0694/PolySharp#107]
### Description (optional)

PolySharp requires "PackageReference" format, but [ASP.NET MVC projects don't support that](https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#:~:text=Migration%20is%20not%20currently%20available%20for%20C%2B%2B%20and%20ASP.NET%20projects.).

### Reproduction Steps

Create ASP.NET MVC project. Try to install PolySharp on it.

### Expected Behavior

It should either work, or the limitation should be documented, so people can make an informed decision to install it. It's currently unclear in PolySharp's documentation that if ASP.NET MVC projects are supported.

### Actual Behavior

It always shows a compiler warning, and possibly doesn't work correctly.

**Comment by Sergio0694** [comment]
This is expected, packages.config doesn't support source generators.

> "the limitation should be documented"

> "It always shows a compiler warning"

That compiler warning is there on purpose specifically to document this and tell you this isn't supported 🙂

**Comment by ssg** [comment]
I don’t think the warning is clear enough (it just says “source generators may not load correctly”, it doesn’t say “this won’t work”), but it’s up to you what to do with it of course.
