### ISSUE TITLE
Polysharp not working with VS17.13

### ISSUE THREAD

**Issue by SoggyBottomBoy** [Sergio0694/PolySharp#115]
### Description (optional)

After upgrading visual studio to 17.13 I am now encountering errors like `Predefined type 'System.Index' is not defined or imported`. I realise this may be a visual studio issue so I have also raised a bug with the vs team, but raising here for visibility just in case.

I should note, build works fine

### Reproduction Steps

Create a .netstandard 2.0 library
Add the polysharp nuget package
Try add the following code:
```csharp
var arr = new double[10];
_ = arr[..2];
```

### System info

This section should contain useful info such as:
- **PolySharp** 1.14.1
- Visual Studio 17.13, .NET 9.0

**Comment by SoggyBottomBoy** [comment]
Also tested with version 1.15.0 and same problem

**Comment by Sergio0694** [comment]
Mmh yeah this sounds like a VS issue.
- Does it work if you do `dotnet build` from cmd?
- Does VS 17.12 work?

**Comment by SoggyBottomBoy** [comment]
Yer `dotnet build` runs fine with no errors reported. 
I will download VS 17.12 now, may just take some time and will let you know.

**Comment by SoggyBottomBoy** [comment]
ok the vs download size is huge. I'll wait until the VS team gets back to me.
https://developercommunity.visualstudio.com/t/Polysharp-no-longer-working-in-VS1713/10796851?port=1025&fsid=e7898644-6137-482c-9115-fa0f24a46869&ref=native&refTime=1732228899290&refUserId=a8afdfb2-4bc7-6b76-9920-032a4f1b8ec1

**Comment by SoggyBottomBoy** [comment]
No issues with VS17.12.1 so I will leave with the VS team.
