### ISSUE TITLE
Dictionary exception when using PolySharp 1.15 with JetBrains Qodana

### ISSUE THREAD

**Issue by dennisdoomen** [Sergio0694/PolySharp#116]
### Description (optional)

Dependabot tried to update [Fluent Assertions](https://github.com/fluentassertions/fluentassertions/) to PolySharp 1.15, but our Qodana (JetBrains static code analysis tool) build hangs because PolySharp throws an exception that a duplicate key.

### Reproduction Steps

See [this pull request](https://github.com/fluentassertions/fluentassertions/pull/2884) as well as the build output [here](https://github.com/fluentassertions/fluentassertions/actions/runs/12359824708/job/34493370009?pr=2884#step:3:137). 

### Expected Behavior

Successful analysis

### Actual Behavior

Qodana hangs and then fails

### System info

This happens on GitHub Actions 

### Additional context (optional)

Love your library!

**Comment by dennisdoomen** [comment]
Never mind. It was caused by Qodana after all. JetBrains will investigate.

**Comment by Sergio0694** [comment]
No worries, glad you figured it out!
