### ISSUE TITLE
Provider a clearer explanation? 

### ISSUE THREAD

**Issue by alexdresko** [Sergio0694/PolySharp#13]
> PolySharp provides generated, source-only polyfills for C# language features, to easily use all runtime-agnostic features downlevel

I know what source generators are, and I know what polyfills are (in general). But I do not know what it means when you say "source-only polyfills for C# language features, to easily use all runtime-agnostic features downlevel"

Being someone who is well versed in .NET and C#, I can't help but think that you'll get more interest in your project if you explain these concepts better in your readme. Maybe even provide some examples. 

The names of the attributes listed in the readme peak my interest, but I do know that some of those attributes already exist... And without further information, I can't invest the time to see if it makes sense for me. 

I figured it was worth writing this issue, thinking that maybe there are others like me.

**Comment by Sergio0694** [comment]
This was a very good point, thank you for the suggestion! 😄
I've improved the readme with a TLDR and a clear example, let me know what you think!
