### ISSUE TITLE
StringSyntaxAttribute not valid with frameworks that do not have Array.Empty

### ISSUE THREAD

**Issue by rsking** [Sergio0694/PolySharp#15]
### Description (optional)

Some older frameworks do not have `Array.Empty`, which causes a compilation failure when including `StringSyntaxAttribute`.

### Reproduction Steps

Target < NET Standard 1.3 or < NET Framework 4.6.

### Expected Behaviour

Compilation succeeds.

### Actual Behaviour

The compilation fails with an error => `error CS0117: 'Array' does not contain a definition for 'Empty'`

### System info

This section should contain useful info such as:
- **PolySharp** 1.6.0
- Windows 11
- Visual Studio 17.3/.NET SDK 6.0.402

### Additional context (optional)

This can be worked around by excluding that generation, but it would be expected to build out of the box.

**Comment by Sergio0694** [comment]
Oof, .NET Standard 1.3 sounds painful! 😅
Fixed, thanks!
