### ISSUE TITLE
`AsyncMethodBuilderAttribute` and `ModuleInitializerAttribute` declared as `public` rather than `internal`

### ISSUE THREAD

**Issue by daviddotcs** [Sergio0694/PolySharp#18]
### Description

`AsyncMethodBuilderAttribute` and `ModuleInitializerAttribute` are declared as `public` rather than `internal` unlike all the other types produced by the source generator, which causes conflicts when PolySharp is used in a library that is referenced by a project which already uses those types.

### Reproduction Steps

* Reference PolySharp in a *netstandard2.0* project (ProjectA)
* Reference ProjectA in a *net6.0* project (ProjectB)
* Attempt to use `[ModuleInitializer]` in ProjectB

### Expected Behavior

The projects should compile and `ModuleInitializerAttribute` be resolved from System.Runtime in ProjectB.

### Actual Behavior

There is a CS0433 error in ProjectB because `ModuleInitializerAttribute` is declared publicly in both ProjectA and System.Runtime.

### System info

- **PolySharp** NuGet version 1.7.0

Thanks for making this, it's neat having all the polyfills in one place and generated as-required via a source generator 🙂.

**Comment by Sergio0694** [comment]
Oops 😅
Fixed by https://github.com/Sergio0694/PolySharp/commit/066835fdd192303336e3edb568a2933c84382fdf, thank you!
