### ISSUE TITLE
Support System.Diagnostics.CodeAnalysis attributes as well

### ISSUE THREAD

**Issue by Brunni** [Sergio0694/PolySharp#26]
In System.Diagnostics.CodeAnalysis are attributes which I would like to use in .netstandard2.0 target projects.

There are a lot of attributes there, which I would like to use:
https://learn.microsoft.com/de-de/dotnet/api/system.diagnostics.codeanalysis?view=net-7.0

e.g. [NotNullWhenAttribute]

The existing nuget is not working correctly: https://www.nuget.org/packages/Compat.System.Diagnostics.CodeAnalysis/

**Comment by Sergio0694** [comment]
All these attributes are already available in PolySharp 🙂

You can see the full list in the readme of this repository.
