### ISSUE TITLE
Update readme and add warning for projects using packages.config

### ISSUE THREAD

**Issue by Sergio0694** [Sergio0694/PolySharp#45]
### Description

Source generators might not be loaded correctly in legacy-style .csproj projects on NETFX (see #39, #43). The readme should include a warning explaining this, with a link to the [SDK-style .csproj project docs](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview) to help users understand how to fix things.

**Comment by cremor** [comment]
I just checked my solution and noticed that I have 2 legacy-style csproj projects in it with PolySharp. And PolySharp works fine in both.

Could it be that the requirement is not strictly about SDK-style projects, but instead just to not use package.config? So legacy-style csproj with <PackageReference> works too?

**Comment by Sergio0694** [comment]
Correction, yes, the issue is not legacy style, the issue is package.config, that's not supported. Using legacy style is fine as long as you're using package reference. I'm also thinking I could add a warning in my .targets to just let users know if they have package.config, why the generator isn't running. That would make the UX much better in case they're not working 🙂

**Comment by cremor** [comment]
> I'm also thinking I could add a warning in my .targets to just let users know if they have package.config, why the generator isn't running. That would make the UX much better in case they're not working

That would be great, yes!

**Comment by AvremelM** [comment]
> Correction, yes, the issue is not legacy style, the issue is package.config, that's not supported. Using legacy style is fine as long as you're using package reference. 

That's a major relief, I was worried this wouldn't work at all for our Web Forms project, which is forever stuck on the old csproj format. But we already switched to using `<PackageReference>` a while ago, so we should (hopefully) be fine.
