### ISSUE TITLE
[Feature request] Add support for RequiresDynamicCodeAttribute

### ISSUE THREAD

**Issue by Shane32** [Sergio0694/PolySharp#51]
### Description

Can this project add support for `RequiresDynamicCodeAttribute`?

### Rationale

This is a .NET 7-only sibling to `RequiresUnreferencedCode`, `DynamicDependency`, and `DynamicallyAccessedMembersAttribute`.  It is needed for proper annotation of 3rd party libraries that include NativeAOT support.

### Reference

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.requiresdynamiccodeattribute?view=net-7.0

**Comment by Sergio0694** [comment]
Oops I somehow missed this one, good catch! Will add it later today 😄

**Comment by Sergio0694** [comment]
Version 1.11.0 is now live on NuGet with this new attribute, thank you for reporting this! 🙂
