### ISSUE TITLE
Compatibility with <LangVersion>11.0</LangVersion> in VS

### ISSUE THREAD

**Issue by jonaskowalczyk** [Sergio0694/PolySharp#57]
Hello,

I have tried to use your package, but when I use <LangVersion>11.0</LangVersion> as a parameter in .csproj and I don't have .NET 7 installed, it says: error CS1617: Invalid option '11.0' for /langversion. Use '/langversion:?' to list supported values.

When I install .NET 7, everything works fine. In my .csproj I am using <TargetFramework>net6.0</TargetFramework> in all cases.

Is there a workaround? 

Thank you.

**Comment by Sergio0694** [comment]
Well, you need the .NET 7 SDK to be able to set the language version to 11.0, there isn't a way around that 🙂
If you don't want to install it, or can't, and you only have the .NET 6 SDK, you can set the version to just 10.0 instead.
