### ISSUE TITLE
support dateonly type

### ISSUE THREAD

**Issue by jismyname** [Sergio0694/PolySharp#58]
there is a struct type named DateOnly in net7.0 under System namespace.

while i installed polysharp  in net48 project , it still appears: type 'DateOnly' could not be found

my project is a sdk project and other features are OK.

**Comment by arphox** [comment]
"PolySharp provides generated, source-only polyfills for **C# language features**"

What you are referring to is not a **C# feature**, but part of a newer .NET version (so, library types/methods).

Maybe you could find a nuget package which adds the type you need, or just could just copy-paste [the implementation](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/DateOnly.cs).

**Anyways, this is unrelated to PolySharp.**

**Comment by Sergio0694** [comment]
Yup, this feature request is out of scope for PolySharp, as it's just a new API in .NET 7 🙂

**Comment by OwnageIsMagic** [comment]
There is
https://github.com/theraot/Theraot
It provides API backports
