### ISSUE TITLE
I followed the instructions, yet the code does not compile.

### ISSUE THREAD

**Issue by YoeriVD** [Sergio0694/PolySharp#61]
VS Code and Rider both recognize the language version, but as soon as I try and compile stuff I get this:
![image](https://user-images.githubusercontent.com/2865793/220900837-fcaca172-6a4a-4614-919e-daf039ba29d8.png)

I created a very simple reproduction repo:
https://github.com/YoeriVD/PolySharpTrial

Any help in what I am missing would be greatly appreciated!

**Comment by Sergio0694** [comment]
You're using MSBuild 17.3. You'll need at least 17.4 to use C# 11.
With 17.3 you can set at most C# 10 level 🙂

**Comment by YoeriVD** [comment]
Thanks @Sergio0694 for the clarification!
But does that mean that I need to install dotnet 7?

![image](https://user-images.githubusercontent.com/2865793/220946985-eb8bb57b-64d8-4748-8036-9f243c9d2959.png)


I can guess why that is necessary, but if that is the case..
May I suggest to add this information to the readme?

**Comment by Sergio0694** [comment]
Yes, for C# 11 you'll need either the .NET 7 SDK, or VS2022 17.4+ (which includes that SDK).
And yeah I could add some stuff to the readme about this, though it'd need to be kept up to date with C# versions.

**Comment by YoeriVD** [comment]
Maybe some generic note saying:
"By the way, eventhough this allows any language version.. you can only target the highest language version your msbuild supports. See this list for more information https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs "
and perhaps reference this issue.



Or something similar. Just a thought :)
