### ISSUE TITLE
How to use it quickly

### ISSUE THREAD

**Issue by wz172** [Sergio0694/PolySharp#66]
I reference this package in netframework4.8, but how do I change the language version, by adding a [Directory.Build.props] file?

**Comment by Sergio0694** [comment]
> "by adding a [Directory.Build.props] file?"

If you want to use a shared .props file, just add this in a `PropertyGroup` in there:

```xml
<LangVersion>11.0</LangVersion>
```

And that's it 🙂

> **Note**: you don't have to set 11.0, you can use whatever version you prefer, 11 is just the latest one.
