### ISSUE TITLE
Would it be possible to use C# 11 language features in .cshtml files?

### ISSUE THREAD

**Issue by RudeySH** [Sergio0694/PolySharp#71]
I have a legacy ASP.NET MVC application built with .NET Framework 4.8, and I'm unable to use constructors of types with `required` members in a .cshtml file. I have installed PolySharp in this project, but I have a feeling something else is required to make it work in .cshtml files.

The error message I'm getting is: 'Constructors of types with required members are not supported in this version of your compiler.'.

Detailed compiler output:

> Microsoft (R) Visual C# Compiler version 4.1.0-5.22114.11 (260d16a8)
Copyright (C) Microsoft Corporation. All rights reserved.
>
> C:\Projects\MyProject\MyProject.Web.Mvc\Views\Shared\\_Layout.cshtml(228,123): error CS0619: 'App.App()' is obsolete: 'Constructors of types with required members are not supported in this version of your compiler.'

I'm using the latest Roslyn CodeDOM provider (4.1.0), which is updated to support `/langversion:11.0`. I have the following configuration in my Web.config:

```
  <system.codedom>
    <compilers>
      <compiler extension=".cs" language="c#;cs;csharp" warningLevel="4" compilerOptions="/langversion:11.0 /nowarn:1659;1699;1701;612;618"
        type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
      <compiler extension=".vb" language="vb;vbs;visualbasic;vbscript" warningLevel="4"
        compilerOptions="/langversion:8.0 /nowarn:41008,40000,40008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+"
        type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
    </compilers>
  </system.codedom>
```

So far I haven't been able to get constructors of types with `required` members to work in .cshtml files. I wonder if it's even possible? Maybe the Roslyn CodeDOM provider needs to reference PolySharp as well?

**Comment by RudeySH** [comment]
I'm not sure what changed, but now I'm getting a different compiler error message:
CS1617: Invalid option '11.0' for /langversion. Use '/langversion:?' to list supported values.

Perhaps I'm misunderstanding what langversion Roslyn CodeDOM provider 4.1.0 supports.

**Comment by Sergio0694** [comment]
I will say that I've never tried this in .cshtml files, so not entirely sure. Have you verified that:
- You're using `<PackageReference>` to reference PolySharp (packages.config won't work)
- You're using an IDE with Roslyn 4.4 or greater (eg. VS 17.4 or greater)

**Comment by RudeySH** [comment]
I'm closing this issue here, because the underlying issue is with RoslynCodeDomProvider: https://github.com/aspnet/RoslynCodeDomProvider/issues/152
