### ISSUE TITLE
How is this project compared to SimonCropp/Polyfill?

### ISSUE THREAD

**Issue by iahung3** [Sergio0694/PolySharp#86]
https://github.com/SimonCropp/Polyfill

**Comment by Sergio0694** [comment]
Hey @iahung3, sorry for the delay! The project has a very different approach than Polyfill: that ships source files, whereas this uses a source generator. The advantage of this is that it automatically generates only the types needed, allows extra customization (you can opt-in and out of any given type, and more options), and it is also able to correctly generate type forwards to ensure things work as expected in multi-targeting scenarios 🙂
