### ISSUE TITLE
How are all the polyfill source files generated?

### ISSUE THREAD

**Issue by 0xced** [Sergio0694/PolySharp#88]
Looking inside `src/PolySharp.SourceGenerators/EmbeddedResources` all polyfill source files are marked as `// <auto-generated/>` but I could not figure out how exactly those files are generated. I was expecting to find a tool inside this repository that was responsible for automatically generating those files, but could not find one! I even tried looking at the commit history to find clues but it did not help. 

@Sergio0694 Could you please shed some light?

Some context: I wanted to contribute a polyfill for `UnreachableException` (issue #60) and I had to copy/paste the code from https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/UnreachableException.cs It felt very much cheating to not use automatic code generation like all other polyfills.

**Comment by Sergio0694** [comment]
Hey there! The polyfills are generated by an incremental generator bundled in the package 🙂
It's this one:

https://github.com/Sergio0694/PolySharp/blob/2689b7e2e70db52c6947b75245948c040417ddf0/src/PolySharp.SourceGenerators/PolyfillsGenerator.cs#L10-L11

**Comment by Sergio0694** [comment]
Oooh gotcha, sorry. Yeah those were just manually added to those files 😄
Those files are not autogenerated in this repo, they're more like templates.

**Comment by 0xced** [comment]
OK, got it. I was totally fooled by the `// <auto-generated/>` comment. I was expecting something like what Simon Cropp does in its NullabilityInfoContext polyfill, i.e. syncing from the dotnet/runtime repository and applying some fixes on top of it: https://github.com/SimonCropp/NullabilityInfo/blob/1e49e8d7f3bb6a2146ea0ca606ab803ac3ceb6ac/src/Nullability.Source.Tests/Sync.cs#L12-L40
